// MITRE ATT&CK tactic identifiers shared across the Settings playbook editor
// and the Knowledge Base playbook UI.
export const TACTIC_OPTIONS = [
  'INITIAL_ACCESS','EXECUTION','PERSISTENCE','PRIVILEGE_ESCALATION','DEFENSE_EVASION',
  'CREDENTIAL_ACCESS','DISCOVERY','LATERAL_MOVEMENT','COLLECTION','EXFILTRATION',
  'COMMAND_AND_CONTROL','IMPACT','RECONNAISSANCE','RESOURCE_DEVELOPMENT',
];
