// ── Incident notification email templating ───────────────────────────────────
// Renders structured, severity-themed HTML emails (with a plain-text fallback)
// so incident alerts are scannable in any mail client. Colors mirror the in-app
// severity palette (red/orange/amber/emerald → CRITICAL/HIGH/MEDIUM/LOW).
export type EmailContent = { subject: string; html: string; text: string };

type SeverityTheme = { label: string; emoji: string; accent: string; tint: string; border: string; text: string };

export const SEVERITY_THEME: Record<string, SeverityTheme> = {
  CRITICAL: { label: 'Critical', emoji: '🔴', accent: '#dc2626', tint: '#fef2f2', border: '#fecaca', text: '#991b1b' },
  HIGH:     { label: 'High',     emoji: '🟠', accent: '#ea580c', tint: '#fff7ed', border: '#fed7aa', text: '#9a3412' },
  MEDIUM:   { label: 'Medium',   emoji: '🟡', accent: '#d97706', tint: '#fffbeb', border: '#fde68a', text: '#92400e' },
  LOW:      { label: 'Low',      emoji: '🟢', accent: '#10b981', tint: '#ecfdf5', border: '#a7f3d0', text: '#065f46' },
};

export function escapeHtml(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// Outer email chrome shared by every notification: colored header band, white
// card, footer. Built with tables + inline styles for broad mail-client support.
function wrapEmailShell(opts: { accent: string; preheader: string; eyebrow: string; heading: string; bodyHtml: string }): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(opts.heading)}</title>
</head>
<body style="margin:0;padding:0;background:#f3f4f6;">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;">${escapeHtml(opts.preheader)}</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f3f4f6;padding:24px 12px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
<tr><td align="center">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.08);">
<tr><td style="background:${opts.accent};padding:20px 28px;">
<div style="color:rgba(255,255,255,0.82);font-size:11px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase;">${escapeHtml(opts.eyebrow)}</div>
<div style="color:#ffffff;font-size:20px;font-weight:700;margin-top:4px;line-height:1.3;">${escapeHtml(opts.heading)}</div>
</td></tr>
<tr><td style="padding:24px 28px;color:#374151;font-size:14px;line-height:1.6;">
${opts.bodyHtml}
</td></tr>
<tr><td style="padding:18px 28px;background:#f9fafb;border-top:1px solid #e5e7eb;color:#6b7280;font-size:11px;line-height:1.5;">
<div style="font-weight:700;color:#0f4f63;font-size:12px;">Generated by AISOC SOAR - Black Box Solutions</div>
<div style="margin-top:2px;color:#9ca3af;">Autonomous SOC Platform. Automated notification; please do not reply.</div>
</td></tr>
</table>
</td></tr>
</table>
</body>
</html>`;
}

export function buildIncidentEmail(input: {
  alertId: string;
  ticket: any;
  sourceIp?: string;
  destIp?: string;
  agentName?: string;
  mitreTags?: string[];
}): EmailContent {
  const { alertId, ticket } = input;
  const priority = String(ticket?.priority || 'MEDIUM').toUpperCase();
  const theme = SEVERITY_THEME[priority] || SEVERITY_THEME.MEDIUM;
  const title = String(ticket?.title || '').trim() || `Alert ${alertId}`;
  const reportBody = String(ticket?.report_body || '').trim();
  const businessImpact = String(ticket?.business_impact || '').trim();
  const affected = Array.isArray(ticket?.affected_systems) ? ticket.affected_systems.filter(Boolean).map(String) : [];
  const mitre = (input.mitreTags || []).filter(Boolean).map(String);
  const confidence = typeof ticket?.confidence === 'number'
    ? Math.round(ticket.confidence * (ticket.confidence <= 1 ? 100 : 1))
    : null;
  const sourceIp = input.sourceIp || 'n/a';
  const destIp = input.destIp || 'n/a';
  const agentName = input.agentName || 'unknown';
  const shortId = alertId.slice(0, 8).toUpperCase();
  const detectedAt = new Date().toUTCString();
  const reasoning = String(ticket?.reasoning?.decision || '').trim();

  const mono = "font-family:'SFMono-Regular',Consolas,'Liberation Mono',Menlo,monospace;";
  const muted = '<span style="color:#9ca3af;">—</span>';
  const chip = (t: string) => `<span style="display:inline-block;margin:2px 4px 2px 0;padding:2px 8px;border-radius:6px;background:${theme.tint};border:1px solid ${theme.border};color:${theme.text};font-size:12px;${mono}">${escapeHtml(t)}</span>`;
  const badge = `<span style="display:inline-block;padding:4px 12px;border-radius:999px;background:${theme.accent};color:#ffffff;font-size:12px;font-weight:700;letter-spacing:.5px;">${theme.emoji}&nbsp;${escapeHtml(theme.label.toUpperCase())}</span>`;

  const rows: Array<[string, string]> = [
    ['Priority', badge],
    ['Incident ID', `<span style="${mono}color:#111827;">${escapeHtml(shortId)}</span>`],
    ['Host / Agent', escapeHtml(agentName)],
    ['Network', `<span style="${mono}">${escapeHtml(sourceIp)}</span> &rarr; <span style="${mono}">${escapeHtml(destIp)}</span>`],
    ['MITRE ATT&CK', mitre.length ? mitre.slice(0, 8).map(chip).join('') : muted],
    ['Confidence', confidence != null ? `<strong>${confidence}%</strong>` : muted],
    ['Affected systems', affected.length ? escapeHtml(affected.join(', ')) : muted],
    ['Detected (UTC)', escapeHtml(detectedAt)],
  ];
  const tableRows = rows.map(([k, v]) => `
    <tr>
      <td style="padding:9px 14px;background:#f9fafb;border-bottom:1px solid #f0f0f0;color:#6b7280;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:.4px;white-space:nowrap;vertical-align:top;width:140px;">${escapeHtml(k)}</td>
      <td style="padding:9px 14px;border-bottom:1px solid #f0f0f0;color:#111827;font-size:13px;vertical-align:top;">${v}</td>
    </tr>`).join('');

  const impactBlock = businessImpact ? `
    <div style="margin-top:16px;padding:12px 16px;background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;">
      <span style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.5px;color:#6b7280;">Business impact</span><br>
      <span style="color:#374151;font-size:13px;">${escapeHtml(businessImpact)}</span>
    </div>` : '';
  const summaryBlock = reportBody ? `
    <div style="margin-top:22px;">
      <div style="font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.6px;color:${theme.text};margin-bottom:8px;">🧠 AI Summary</div>
      <div style="background:${theme.tint};border-left:4px solid ${theme.accent};border-radius:0 8px 8px 0;padding:14px 16px;color:#374151;font-size:14px;line-height:1.65;">${escapeHtml(reportBody).replace(/\n/g, '<br>')}</div>
    </div>` : '';
  const reasoningBlock = reasoning ? `
    <div style="margin-top:16px;color:#6b7280;font-size:12px;line-height:1.6;">
      <strong style="color:#4b5563;">Why this priority:</strong> ${escapeHtml(reasoning)}
    </div>` : '';

  const bodyHtml = `
    <p style="margin:0 0 18px;font-size:14px;color:#374151;">A new <strong style="color:${theme.text};">${escapeHtml(theme.label.toLowerCase())}-severity</strong> incident has been detected and triaged by the AISOC pipeline.</p>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #f0f0f0;border-radius:8px;overflow:hidden;">${tableRows}</table>
    ${impactBlock}
    ${summaryBlock}
    ${reasoningBlock}`;

  const html = wrapEmailShell({
    accent: theme.accent,
    preheader: `${theme.label} incident: ${title}`,
    eyebrow: `${theme.label} Incident Alert`,
    heading: title,
    bodyHtml,
  });

  const text = [
    `[BBS AISOC] ${priority} INCIDENT`,
    title,
    '',
    `Priority:         ${priority}`,
    `Incident ID:      ${shortId}`,
    `Host / Agent:     ${agentName}`,
    `Network:          ${sourceIp} -> ${destIp}`,
    `MITRE ATT&CK:     ${mitre.length ? mitre.join(', ') : '—'}`,
    `Confidence:       ${confidence != null ? confidence + '%' : '—'}`,
    `Affected systems: ${affected.length ? affected.join(', ') : '—'}`,
    `Detected (UTC):   ${detectedAt}`,
    businessImpact ? `\nBusiness impact:\n${businessImpact}` : '',
    reportBody ? `\nAI Summary:\n${reportBody}` : '',
    reasoning ? `\nWhy this priority:\n${reasoning}` : '',
    '\nGenerated by AISOC SOAR - Black Box Solutions',
  ].filter(Boolean).join('\n');

  return { subject: `${theme.emoji} ${theme.label.toUpperCase()} — ${title}`, html, text };
}

export function buildTestEmail(): EmailContent {
  const accent = '#2563eb';
  const bodyHtml = `
    <p style="margin:0 0 14px;font-size:14px;color:#374151;">✅ Your email integration is working correctly.</p>
    <p style="margin:0;font-size:14px;color:#374151;">This is a test notification from the <strong>BBS AISOC</strong> platform. Real incident alerts will arrive here with a structured, severity-colored layout that summarizes each detection at a glance.</p>`;
  return {
    subject: 'Email integration test',
    html: wrapEmailShell({
      accent,
      preheader: 'BBS AISOC email integration test',
      eyebrow: 'Integration Test',
      heading: 'Email notifications are configured',
      bodyHtml,
    }),
    text: 'BBS AISOC — Email integration test\n\nThis is a test notification from the BBS AISOC platform. If you received this, email integration is working correctly.\n\nGenerated by AISOC SOAR - Black Box Solutions',
  };
}
